import { TarotCard, SpreadType } from './types';

export const TAROT_DECK: TarotCard[] = [
  // Major Arcana
  {
    id: 'maj_0',
    name: 'The Fool',
    arcana: 'Major',
    keywords: ['Beginnings', 'Innocence', 'Spontaneity', 'Free Spirit'],
    meaning: 'A new journey is beginning. Embrace the unknown with open arms and a sense of wonder.',
    reversedMeaning: 'Holding back, recklessness, risk-aversion. You may be paralyzed by fear of the unknown.',
    microQuest: 'Do one small thing today you have never done before.',
    element: 'Air',
  },
  {
    id: 'maj_1',
    name: 'The Magician',
    arcana: 'Major',
    keywords: ['Manifestation', 'Resourcefulness', 'Power', 'Inspired Action'],
    meaning: 'You have all the tools and resources you need to manifest your desires. It is time to take action.',
    reversedMeaning: 'Manipulation, poor planning, untapped talents. Your potential is not being used effectively.',
    microQuest: 'Identify one skill you have and use it to make progress on a goal.',
    element: 'Air',
  },
  {
    id: 'maj_2',
    name: 'The High Priestess',
    arcana: 'Major',
    keywords: ['Intuition', 'Unconscious', 'Inner Voice', 'Secrets'],
    meaning: 'Trust your intuition and look beyond the obvious. The answers you seek are within you.',
    reversedMeaning: 'Secrets revealed, lack of intuition, repressed feelings. You are disconnected from your inner voice.',
    microQuest: 'Spend five minutes in silence, just listening to your thoughts without judgment.',
    element: 'Water',
  },
  {
    id: 'maj_3',
    name: 'The Empress',
    arcana: 'Major',
    keywords: ['Fertility', 'Femininity', 'Beauty', 'Nature', 'Abundance'],
    meaning: 'A time of creativity, growth, and nurturing. Embrace your connection to the natural world.',
    reversedMeaning: 'Creative block, dependence on others, stagnation. You feel disconnected from your creativity.',
    microQuest: 'Nourish yourself with a good meal or spend some time in nature.',
    element: 'Earth',
  },
  {
    id: 'maj_4',
    name: 'The Emperor',
    arcana: 'Major',
    keywords: ['Authority', 'Structure', 'Control', 'Father Figure'],
    meaning: 'Establish order and structure in your life. A disciplined approach will lead to success.',
    reversedMeaning: 'Domination, excessive control, lack of discipline, rigidity. You are either too controlling or lack control.',
    microQuest: 'Create a plan or a to-do list for your day and stick to it.',
    element: 'Fire',
  },
  {
    id: 'maj_5',
    name: 'The Hierophant',
    arcana: 'Major',
    keywords: ['Tradition', 'Conformity', 'Morality', 'Ethics'],
    meaning: 'Seek wisdom from established traditions and institutions. Follow a conventional path.',
    reversedMeaning: 'Rebellion, non-conformity, new approaches. It is time to challenge tradition and find your own way.',
    microQuest: 'Learn about a tradition or belief system that is different from your own.',
    element: 'Earth',
  },
  {
    id: 'maj_6',
    name: 'The Lovers',
    arcana: 'Major',
    keywords: ['Love', 'Harmony', 'Relationships', 'Values Alignment'],
    meaning: 'A significant choice about a relationship or your personal values is at hand. Choose with your heart.',
    reversedMeaning: 'Disharmony, imbalance, misalignment of values. A relationship may be out of sync.',
    microQuest: 'Identify one of your core values and make a small decision that aligns with it.',
    element: 'Air',
  },
  {
    id: 'maj_7',
    name: 'The Chariot',
    arcana: 'Major',
    keywords: ['Control', 'Willpower', 'Victory', 'Assertion'],
    meaning: 'Move forward with determination and willpower. You can overcome any obstacle in your path.',
    reversedMeaning: 'Lack of direction, aggression, self-discipline. Your energy is scattered and lacks focus.',
    microQuest: 'Take one decisive step towards a goal you have been procrastinating on.',
    element: 'Water',
  },
  {
    id: 'maj_8',
    name: 'Strength',
    arcana: 'Major',
    keywords: ['Courage', 'Patience', 'Compassion', 'Self-Control'],
    meaning: 'True strength comes from within. Use compassion and gentle persuasion, not brute force.',
    reversedMeaning: 'Weakness, self-doubt, lack of self-control. You are letting fear or impulse guide you.',
    microQuest: 'Face a small fear today with courage and compassion for yourself.',
    element: 'Fire',
  },
  {
    id: 'maj_9',
    name: 'The Hermit',
    arcana: 'Major',
    keywords: ['Soul-searching', 'Introspection', 'Guidance', 'Solitude'],
    meaning: 'It is time for introspection and soul-searching. Withdraw from the world to find your inner guidance.',
    reversedMeaning: 'Isolation, loneliness, withdrawal. You are either too isolated or avoiding necessary solitude.',
    microQuest: 'Spend some time alone today, even if it is just for 15 minutes, without digital distractions.',
    element: 'Earth',
  },
  {
    id: 'maj_10',
    name: 'Wheel of Fortune',
    arcana: 'Major',
    keywords: ['Good luck', 'Karma', 'Life cycles', 'Destiny', 'A turning point'],
    meaning: 'A turning point is here. The wheel of fortune is spinning in your favor. Embrace change.',
    reversedMeaning: 'Bad luck, resistance to change, breaking cycles. You are experiencing a downswing or resisting fate.',
    microQuest: 'Acknowledge one thing in your life that is outside of your control and accept it.',
    element: 'Fire',
  },
  {
    id: 'maj_11',
    name: 'Justice',
    arcana: 'Major',
    keywords: ['Justice', 'Fairness', 'Truth', 'Cause and Effect', 'Law'],
    meaning: 'Seek fairness and truth in all your dealings. Your actions have consequences, so act with integrity.',
    reversedMeaning: 'Unfairness, lack of accountability, dishonesty. There is an injustice that needs to be addressed.',
    microQuest: 'Make a decision today that is fair to everyone involved, including yourself.',
    element: 'Air',
  },
  {
    id: 'maj_12',
    name: 'The Hanged Man',
    arcana: 'Major',
    keywords: ['Pause', 'Surrender', 'Letting go', 'New perspectives'],
    meaning: 'A pause is necessary. Let go of control and look at things from a new perspective.',
    reversedMeaning: 'Stalling, needless sacrifice, resistance. You are stuck and refusing to see a different way.',
    microQuest: 'If you feel stuck on a problem, stop trying to solve it for an hour. Let your mind rest.',
    element: 'Water',
  },
  {
    id: 'maj_13',
    name: 'Death',
    arcana: 'Major',
    keywords: ['Endings', 'Change', 'Transformation', 'Transition'],
    meaning: 'An ending is here, but it brings with it a necessary transformation. Let go of what is no longer serving you.',
    reversedMeaning: 'Resistance to change, fear of endings, stagnation. You are clinging to the past.',
    microQuest: 'Identify one thing you can let go of today, whether it is a physical object or a negative thought.',
    element: 'Water',
  },
  {
    id: 'maj_14',
    name: 'Temperance',
    arcana: 'Major',
    keywords: ['Balance', 'Moderation', 'Patience', 'Finding middle ground'],
    meaning: 'Find balance and moderation in your life. Patience and a calm approach are needed.',
    reversedMeaning: 'Imbalance, excess, extremes. You are going to one extreme or another.',
    microQuest: 'Find a middle ground in a situation where you have been seeing things in black and white.',
    element: 'Fire',
  },
  {
    id: 'maj_15',
    name: 'The Devil',
    arcana: 'Major',
    keywords: ['Bondage', 'Addiction', 'Sexuality', 'Materialism'],
    meaning: 'You are feeling trapped by your own limiting beliefs, habits, or addictions. It is time to face your shadow self.',
    reversedMeaning: 'Breaking free, detachment, release. You are recognizing and breaking free from your chains.',
    microQuest: 'Acknowledge one limiting belief you hold about yourself.',
    element: 'Earth',
  },
  {
    id: 'maj_16',
    name: 'The Tower',
    arcana: 'Major',
    keywords: ['Sudden change', 'Upheaval', 'Chaos', 'Revelation', 'Awakening'],
    meaning: 'A sudden, dramatic change is coming that will shake your foundations. It is a necessary destruction to build anew.',
    reversedMeaning: 'Fear of change, avoiding disaster. You are trying to prevent an inevitable change.',
    microQuest: 'Challenge one assumption you have held for a long time.',
    element: 'Fire',
  },
  {
    id: 'maj_17',
    name: 'The Star',
    arcana: 'Major',
    keywords: ['Hope', 'Faith', 'Purpose', 'Rejuvenation', 'Spirituality'],
    meaning: 'A time of hope and inspiration. Have faith in the future and your connection to the divine.',
    reversedMeaning: 'Lack of faith, despair, disconnection. You have lost hope and feel disconnected from your purpose.',
    microQuest: 'Look up at the stars tonight and make a wish for the future.',
    element: 'Air',
  },
  {
    id: 'maj_18',
    name: 'The Moon',
    arcana: 'Major',
    keywords: ['Illusion', 'Fear', 'Anxiety', 'Subconscious', 'Intuition'],
    meaning: 'Things are not as they seem. Trust your intuition to guide you through this time of uncertainty and illusion.',
    reversedMeaning: 'Release of fear, clarity, understanding. You are beginning to see through the illusion.',
    microQuest: 'Pay attention to your dreams tonight and write down what you remember.',
    element: 'Water',
  },
  {
    id: 'maj_19',
    name: 'The Sun',
    arcana: 'Major',
    keywords: ['Positivity', 'Fun', 'Warmth', 'Success', 'Vitality'],
    meaning: 'A time of great joy, success, and vitality. Embrace the positivity and warmth surrounding you.',
    reversedMeaning: 'Lack of success, pessimism. You are struggling to see the bright side of things.',
    microQuest: 'Do something today just for fun, without any other goal in mind.',
    element: 'Fire',
  },
  {
    id: 'maj_20',
    name: 'Judgement',
    arcana: 'Major',
    keywords: ['Rebirth', 'Inner Calling', 'Absolution', 'Awakening'],
    meaning: 'A spiritual awakening is at hand. It is time to answer your inner calling and make a final judgment.',
    reversedMeaning: 'Self-doubt, ignoring the call. You are afraid to make a necessary decision.',
    microQuest: 'Reflect on your past actions with forgiveness and decide how you want to move forward.',
    element: 'Fire',
  },
  {
    id: 'maj_21',
    name: 'The World',
    arcana: 'Major',
    keywords: ['Completion', 'Integration', 'Accomplishment', 'Travel'],
    meaning: 'A cycle is coming to a successful close. Acknowledge your accomplishments and celebrate your journey.',
    reversedMeaning: 'Lack of closure, incompletion, shortcuts. You may be seeking closure that has not yet been earned.',
    microQuest: 'Reflect on a recent accomplishment, big or small, and write down what you learned.',
    element: 'Earth',
  },
  // Wands
  {
    id: 'wands_1',
    name: 'Ace of Wands',
    arcana: 'Wands',
    keywords: ['Inspiration', 'New opportunities', 'Growth', 'Potential'],
    meaning: 'A spark of a new idea or opportunity has arrived. Seize this moment of inspiration and run with it.',
    reversedMeaning: 'Lack of energy, lack of passion, boredom. Inspiration is blocked or being ignored.',
    microQuest: 'Brainstorm three new ideas related to a project you care about.',
    element: 'Fire',
  },
  {
    id: 'wands_2',
    name: 'Two of Wands',
    arcana: 'Wands',
    keywords: ['Future planning', 'Progress', 'Decisions', 'Discovery'],
    meaning: 'You are at a crossroads, planning for the future. You have made progress and now must decide the next step.',
    reversedMeaning: 'Fear of the unknown, lack of planning. You are stuck in your comfort zone.',
    microQuest: 'Write down one long-term goal and the very first step you can take to achieve it.',
    element: 'Fire',
  },
  {
    id: 'wands_3',
    name: 'Three of Wands',
    arcana: 'Wands',
    keywords: ['Expansion', 'Foresight', 'Overseas Opportunities', 'Progress'],
    meaning: 'Your plans are in motion and you are seeing the first signs of success. Look to the future with optimism.',
    reversedMeaning: 'Delays, obstacles to long-term goals. Your plans are not unfolding as expected.',
    microQuest: 'Think about where you want to be in six months. Visualize it.',
    element: 'Fire',
  },
  {
    id: 'wands_4',
    name: 'Four of Wands',
    arcana: 'Wands',
    keywords: ['Celebration', 'Harmony', 'Marriage', 'Home', 'Community'],
    meaning: 'A time of celebration and harmony, especially related to home and community. Enjoy this moment of peace.',
    reversedMeaning: 'Lack of support, instability, feeling unwelcome. There is a lack of harmony in your home or community.',
    microQuest: 'Celebrate a small victory with someone you care about.',
    element: 'Fire',
  },
  {
    id: 'wands_5',
    name: 'Five of Wands',
    arcana: 'Wands',
    keywords: ['Conflict', 'Competition', 'Disagreements', 'Tension'],
    meaning: 'You are facing competition or conflict. While challenging, this can lead to growth and new ideas.',
    reversedMeaning: 'Avoiding conflict, finding common ground. The conflict is ending or you are choosing to avoid it.',
    microQuest: 'Listen to an opposing viewpoint today with the intent to understand, not to argue.',
    element: 'Fire',
  },
  {
    id: 'wands_6',
    name: 'Six of Wands',
    arcana: 'Wands',
    keywords: ['Success', 'Public recognition', 'Victory', 'Progress'],
    meaning: 'You have achieved a significant victory and are receiving public recognition for your efforts. Enjoy your success.',
    reversedMeaning: 'Lack of recognition, failure, egotism. Your success is either unrecognized or feeding your ego.',
    microQuest: 'Share a recent success with others, no matter how small.',
    element: 'Fire',
  },
  {
    id: 'wands_7',
    name: 'Seven of Wands',
    arcana: 'Wands',
    keywords: ['Challenge', 'Competition', 'Perseverance', 'Defensive'],
    meaning: 'You are in a position of strength, but you must defend it. Stand your ground and persevere.',
    reversedMeaning: 'Giving up, feeling overwhelmed. You are feeling exhausted by the constant battle.',
    microQuest: 'Stand up for something you believe in today, even in a small way.',
    element: 'Fire',
  },
  {
    id: 'wands_8',
    name: 'Eight of Wands',
    arcana: 'Wands',
    keywords: ['Speed', 'Action', 'Air travel', 'Movement', 'Swift change'],
    meaning: 'Events are moving quickly. A time of rapid action and progress is upon you.',
    reversedMeaning: 'Delays, frustration, slowing down. Things are not moving as quickly as you would like.',
    microQuest: 'Make a quick decision on something you have been hesitating on.',
    element: 'Fire',
  },
  {
    id: 'wands_9',
    name: 'Nine of Wands',
    arcana: 'Wands',
    keywords: ['Resilience', 'Courage', 'Persistence', 'Test of faith'],
    meaning: 'You are wounded but not defeated. You have the resilience to face one final challenge.',
    reversedMeaning: 'Exhaustion, giving up, paranoia. You are on the verge of giving up.',
    microQuest: 'Acknowledge your own resilience. Think of a past challenge you overcame.',
    element: 'Fire',
  },
  {
    id: 'wands_10',
    name: 'Ten of Wands',
    arcana: 'Wands',
    keywords: ['Burden', 'Responsibility', 'Hard work', 'Stress'],
    meaning: 'You are carrying a heavy burden. While you are close to the finish line, do not be afraid to ask for help.',
    reversedMeaning: 'Letting go of burdens, delegation. You are learning to delegate and release your burdens.',
    microQuest: 'Identify one task you can delegate or ask for help with today.',
    element: 'Fire',
  },
  {
    id: 'wands_page',
    name: 'Page of Wands',
    arcana: 'Wands',
    keywords: ['Enthusiasm', 'Exploration', 'Free spirit', 'New ideas'],
    meaning: 'A message of inspiration or a new idea is coming. Embrace your creativity and enthusiasm.',
    reversedMeaning: 'Creative blocks, lack of direction. You are feeling uninspired and unsure of which path to take.',
    microQuest: 'Explore a new hobby or interest online for 15 minutes.',
    element: 'Fire',
  },
  {
    id: 'wands_knight',
    name: 'Knight of Wands',
    arcana: 'Wands',
    keywords: ['Energy', 'Passion', 'Adventure', 'Impulsiveness'],
    meaning: 'Charge forward with energy and passion. A time for bold action and adventure.',
    reversedMeaning: 'Haste, scattered energy, recklessness. Your impulsiveness is leading to poor decisions.',
    microQuest: 'Channel your energy into a physical activity, like a brisk walk or a workout.',
    element: 'Fire',
  },
  {
    id: 'wands_queen',
    name: 'Queen of Wands',
    arcana: 'Wands',
    keywords: ['Courage', 'Confidence', 'Independence', 'Social butterfly'],
    meaning: 'You are confident, courageous, and full of life. Lead with your heart and inspire others.',
    reversedMeaning: 'Selfishness, jealousy, insecurity. Your confidence has turned into arrogance or insecurity.',
    microQuest: 'Be the cheerleader for a friend or colleague today.',
    element: 'Fire',
  },
  {
    id: 'wands_king',
    name: 'King of Wands',
    arcana: 'Wands',
    keywords: ['Natural-born leader', 'Vision', 'Entrepreneur', 'Honour'],
    meaning: 'You are a visionary leader. Take control of your life and inspire others to follow your vision.',
    reversedMeaning: 'Ruthlessness, high expectations, impulsiveness. Your leadership has become tyrannical.',
    microQuest: 'Take the lead on a project, at home or at work, and articulate your vision clearly.',
    element: 'Fire',
  },
  // Cups
  {
    id: 'cups_1',
    name: 'Ace of Cups',
    arcana: 'Cups',
    keywords: ['Love', 'New relationships', 'Compassion', 'Creativity'],
    meaning: 'A new emotional beginning is here. Open your heart to love, compassion, and creativity.',
    reversedMeaning: 'Blocked emotions, emptiness. You are emotionally closed off.',
    microQuest: 'Do one small act of kindness for someone else.',
    element: 'Water',
  },
  {
    id: 'cups_2',
    name: 'Two of Cups',
    arcana: 'Cups',
    keywords: ['Unified love', 'Partnership', 'Mutual attraction'],
    meaning: 'A deep connection and partnership is forming. This is a time of mutual respect and love.',
    reversedMeaning: 'Break-up, disharmony, distrust. A relationship is out of balance.',
    microQuest: 'Connect with a friend or partner and express your appreciation for them.',
    element: 'Water',
  },
  {
    id: 'cups_3',
    name: 'Three of Cups',
    arcana: 'Cups',
    keywords: ['Celebration', 'Friendship', 'Creativity', 'Community'],
    meaning: 'A time of celebration with friends and community. Enjoy the joyful connections in your life.',
    reversedMeaning: 'Gossip, isolation. You are feeling disconnected from your community.',
    microQuest: 'Reach out to a friend you have not spoken to in a while.',
    element: 'Water',
  },
  {
    id: 'cups_4',
    name: 'Four of Cups',
    arcana: 'Cups',
    keywords: ['Apathy', 'Contemplation', 'Disconnection', 'Re-evaluation'],
    meaning: 'You are feeling apathetic and disconnected. A new opportunity is being offered, but you may not see it.',
    reversedMeaning: 'Sudden awareness, choosing happiness. You are ready to embrace new opportunities.',
    microQuest: 'Take a moment to notice one beautiful thing around you that you usually overlook.',
    element: 'Water',
  },
  {
    id: 'cups_5',
    name: 'Five of Cups',
    arcana: 'Cups',
    keywords: ['Loss', 'Regret', 'Disappointment', 'Grief'],
    meaning: 'You are focusing on a past loss or disappointment. While it is important to grieve, do not forget what you still have.',
    reversedMeaning: 'Moving on, acceptance, forgiveness. You are ready to let go of regret and move forward.',
    microQuest: 'Acknowledge one thing you are grateful for, even in a difficult time.',
    element: 'Water',
  },
  {
    id: 'cups_6',
    name: 'Six of Cups',
    arcana: 'Cups',
    keywords: ['Nostalgia', 'Childhood memories', 'Reunion', 'Innocence'],
    meaning: 'A connection to the past brings comfort and joy. This may be a time of nostalgia or reunion.',
    reversedMeaning: 'Stuck in the past, moving forward. You are either clinging to the past or ready to let it go.',
    microQuest: 'Look at an old photo and reflect on a happy memory.',
    element: 'Water',
  },
  {
    id: 'cups_7',
    name: 'Seven of Cups',
    arcana: 'Cups',
    keywords: ['Choices', 'Illusion', 'Fantasy', 'Opportunities'],
    meaning: 'You have many choices before you, but some may be illusions. You need to distinguish fantasy from reality.',
    reversedMeaning: 'Clarity, making a decision. You are finally seeing your choices clearly.',
    microQuest: 'Write down the pros and cons of one decision you are facing.',
    element: 'Water',
  },
  {
    id: 'cups_8',
    name: 'Eight of Cups',
    arcana: 'Cups',
    keywords: ['Abandonment', 'Withdrawal', 'Escapism', 'Moving on'],
    meaning: 'It is time to walk away from a situation that is no longer emotionally fulfilling. Seek a deeper meaning.',
    reversedMeaning: 'Fear of moving on, stagnation. You are afraid to leave a comfortable but unfulfilling situation.',
    microQuest: 'Identify one thing in your life that is draining your emotional energy.',
    element: 'Water',
  },
  {
    id: 'cups_9',
    name: 'Nine of Cups',
    arcana: 'Cups',
    keywords: ['Wishes fulfilled', 'Contentment', 'Satisfaction', 'Gratitude'],
    meaning: 'Your wishes are coming true. This is a time of contentment, satisfaction, and gratitude.',
    reversedMeaning: 'Dissatisfaction, materialism. Your desires are not bringing you the happiness you expected.',
    microQuest: 'Make a list of three things you are truly content with in your life right now.',
    element: 'Water',
  },
  {
    id: 'cups_10',
    name: 'Ten of Cups',
    arcana: 'Cups',
    keywords: ['Harmony', 'Marriage', 'Happiness', 'Alignment'],
    meaning: 'You are experiencing divine love and emotional fulfillment. This is a time of harmony and happiness.',
    reversedMeaning: 'Misaligned values, broken home, disharmony. Your relationships may be out of sync with your true self.',
    microQuest: 'Express gratitude to a loved one for the harmony they bring to your life.',
    element: 'Water',
  },
  {
    id: 'cups_page',
    name: 'Page of Cups',
    arcana: 'Cups',
    keywords: ['Creative opportunities', 'Intuition', 'Curiosity', 'Possibility'],
    meaning: 'A message of creative opportunity or a new emotional experience is on its way. Stay open.',
    reversedMeaning: 'Emotional immaturity, creative blocks. You are struggling to express your feelings creatively.',
    microQuest: 'Try a creative activity, like drawing or writing, for just 10 minutes.',
    element: 'Water',
  },
  {
    id: 'cups_knight',
    name: 'Knight of Cups',
    arcana: 'Cups',
    keywords: ['Romance', 'Charm', 'Imagination', 'Beauty'],
    meaning: 'You are a romantic and an idealist, guided by your heart. An offer of love may be coming.',
    reversedMeaning: 'Unrealistic expectations, moodiness. Your idealism is leading to disappointment.',
    microQuest: 'Do something romantic, for yourself or for a partner.',
    element: 'Water',
  },
  {
    id: 'cups_queen',
    name: 'Queen of Cups',
    arcana: 'Cups',
    keywords: ['Compassion', 'Calm', 'Intuitive', 'Nurturing'],
    meaning: 'You are emotionally mature and intuitive. Lead with compassion and trust your inner voice.',
    reversedMeaning: 'Emotional insecurity, co-dependency. You are letting your emotions control you.',
    microQuest: 'Offer a listening ear to someone who needs it today.',
    element: 'Water',
  },
  {
    id: 'cups_king',
    name: 'King of Cups',
    arcana: 'Cups',
    keywords: ['Emotional balance', 'Control', 'Compassion', 'Diplomacy'],
    meaning: 'You are in control of your emotions and can offer wise, compassionate counsel. You are a master of your feelings.',
    reversedMeaning: 'Emotional manipulation, moodiness, volatility. Your emotions are out of control.',
    microQuest: 'Respond to a challenging situation today with calm and compassion.',
    element: 'Water',
  },
  // Swords
  {
    id: 'swords_1',
    name: 'Ace of Swords',
    arcana: 'Swords',
    keywords: ['Breakthroughs', 'New ideas', 'Mental clarity', 'Success'],
    meaning: 'A moment of breakthrough and mental clarity. A new idea has the power to cut through confusion.',
    reversedMeaning: 'Confusion, clouded judgment. Your thinking is unclear.',
    microQuest: 'Articulate a complex problem you are facing in a single, clear sentence.',
    element: 'Air',
  },
  {
    id: 'swords_2',
    name: 'Two of Swords',
    arcana: 'Swords',
    keywords: ['Difficult choices', 'Indecision', 'Stalemate', 'Blocked emotions'],
    meaning: 'You are facing a difficult choice and are at a stalemate. You may be blocking your emotions to make a logical decision.',
    reversedMeaning: 'Indecision, confusion, information overload. You are struggling to make a choice.',
    microQuest: 'Give yourself a deadline to make a small decision you have been putting off.',
    element: 'Air',
  },
  {
    id: 'swords_3',
    name: 'Three of Swords',
    arcana: 'Swords',
    keywords: ['Heartbreak', 'Grief', 'Sorrow', 'Rejection'],
    meaning: 'Painful truths and necessary heartbreaks are clearing the way for new understanding. Allow yourself to feel the sorrow.',
    reversedMeaning: 'Releasing pain, optimism, forgiveness. You are moving through grief and finding a path to healing.',
    microQuest: 'Acknowledge one painful feeling without judgment. Let it be, just for a moment.',
    element: 'Air',
  },
  {
    id: 'swords_4',
    name: 'Four of Swords',
    arcana: 'Swords',
    keywords: ['Rest', 'Relaxation', 'Meditation', 'Contemplation'],
    meaning: 'A period of rest and recuperation is needed. Take a break to recharge your mental batteries.',
    reversedMeaning: 'Exhaustion, burnout, stagnation. You are in desperate need of a break.',
    microQuest: 'Schedule a 15-minute break in your day where you do absolutely nothing.',
    element: 'Air',
  },
  {
    id: 'swords_5',
    name: 'Five of Swords',
    arcana: 'Swords',
    keywords: ['Conflict', 'Disagreements', 'Competition', 'Defeat', 'Win at all costs'],
    meaning: 'A conflict where winning comes at a great cost. Be mindful of the consequences of your actions.',
    reversedMeaning: 'Reconciliation, making amends. It is time to end the conflict and seek peace.',
    microQuest: 'Consider if "winning" an argument is more important than the relationship itself.',
    element: 'Air',
  },
  {
    id: 'swords_6',
    name: 'Six of Swords',
    arcana: 'Swords',
    keywords: ['Transition', 'Change', 'Rite of passage', 'Releasing baggage'],
    meaning: 'You are moving from a difficult past into a calmer future. It is a time of transition and leaving baggage behind.',
    reversedMeaning: 'Inability to move on, carrying baggage. You are stuck in the past.',
    microQuest: 'Identify one piece of "mental baggage" you can choose to leave behind today.',
    element: 'Air',
  },
  {
    id: 'swords_7',
    name: 'Seven of Swords',
    arcana: 'Swords',
    keywords: ['Deception', 'Betrayal', 'Secrecy', 'Strategy'],
    meaning: 'There may be deception or betrayal at play. You may need to act strategically to get what you want.',
    reversedMeaning: 'Coming clean, confession. Secrets are being revealed.',
    microQuest: 'Be radically honest with yourself about one thing you have been avoiding.',
    element: 'Air',
  },
  {
    id: 'swords_8',
    name: 'Eight of Swords',
    arcana: 'Swords',
    keywords: ['Self-imposed restriction', 'Imprisonment', 'Limiting beliefs', 'Victim mentality'],
    meaning: 'You feel trapped, but the restrictions are self-imposed. Change your perspective to find your freedom.',
    reversedMeaning: 'Breaking free, release, new perspective. You are realizing you have the power to free yourself.',
    microQuest: 'Challenge one "I can\'t" thought you have today.',
    element: 'Air',
  },
  {
    id: 'swords_9',
    name: 'Nine of Swords',
    arcana: 'Swords',
    keywords: ['Anxiety', 'Worry', 'Fear', 'Depression', 'Nightmares'],
    meaning: 'You are plagued by anxiety and fear. Your negative thoughts are creating your reality.',
    reversedMeaning: 'Release of worry, finding help. You are finding ways to cope with your anxiety.',
    microQuest: 'Write down your biggest worry on a piece of paper, then tear it up.',
    element: 'Air',
  },
  {
    id: 'swords_10',
    name: 'Ten of Swords',
    arcana: 'Swords',
    keywords: ['Painful endings', 'Betrayal', 'Loss', 'Crisis', 'Rock bottom'],
    meaning: 'You have hit rock bottom. This painful ending is final, but it also means the only way is up.',
    reversedMeaning: 'Recovery, regeneration, resisting the inevitable end. You are slowly recovering from a painful end.',
    microQuest: 'Acknowledge that an ending can be a new beginning.',
    element: 'Air',
  },
  {
    id: 'swords_page',
    name: 'Page of Swords',
    arcana: 'Swords',
    keywords: ['New ideas', 'Curiosity', 'Thirst for knowledge', 'Energy'],
    meaning: 'You are full of new ideas and a thirst for knowledge. Speak your truth and ask questions.',
    reversedMeaning: 'Gossip, scattered thoughts. Your words may be hurtful or your thoughts unfocused.',
    microQuest: 'Learn one new fact about a topic that interests you.',
    element: 'Air',
  },
  {
    id: 'swords_knight',
    name: 'Knight of Swords',
    arcana: 'Swords',
    keywords: ['Ambitious', 'Action-oriented', 'Fast-thinking', 'Driven'],
    meaning: 'You are driven and ambitious, charging forward with your ideas. Act quickly and decisively.',
    reversedMeaning: 'Reckless, impulsive, burnout. Your haste is causing problems.',
    microQuest: 'Take one decisive action on an idea you have been contemplating.',
    element: 'Air',
  },
  {
    id: 'swords_queen',
    name: 'Queen of Swords',
    arcana: 'Swords',
    keywords: ['Independent', 'Unbiased judgment', 'Clear boundaries', 'Intellect'],
    meaning: 'You are a sharp thinker with clear boundaries. Use your intellect to cut through the noise and find the truth.',
    reversedMeaning: 'Cold, cruel, bitter. Your words are being used to hurt others.',
    microQuest: 'Set a clear boundary with someone today in a fair and direct way.',
    element: 'Air',
  },
  {
    id: 'swords_king',
    name: 'King of Swords',
    arcana: 'Swords',
    keywords: ['Mental clarity', 'Intellectual power', 'Authority', 'Truth'],
    meaning: 'You are a master of logic and reason. You can see the truth of any situation with clarity and authority.',
    reversedMeaning: 'Misuse of power, manipulation, cruelty. Your intellect is being used for selfish or cruel ends.',
    microQuest: 'Offer objective advice to someone, free from emotional bias.',
    element: 'Air',
  },
  // Pentacles
  {
    id: 'pents_1',
    name: 'Ace of Pentacles',
    arcana: 'Pentacles',
    keywords: ['New opportunity', 'Prosperity', 'Manifestation', 'Abundance'],
    meaning: 'A seed of prosperity has been planted. This is a time of new opportunities in the material world.',
    reversedMeaning: 'Lost opportunity, poor financial planning. An opportunity has been missed.',
    microQuest: 'Take one small, practical step towards a financial or career goal.',
    element: 'Earth',
  },
  {
    id: 'pents_2',
    name: 'Two of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Balance', 'Priorities', 'Adaptability', 'Time management'],
    meaning: 'You are juggling multiple priorities. Stay balanced and adaptable to manage everything successfully.',
    reversedMeaning: 'Overwhelmed, disorganization. You are struggling to keep everything in balance.',
    microQuest: 'Prioritize your top three tasks for the day.',
    element: 'Earth',
  },
  {
    id: 'pents_3',
    name: 'Three of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Teamwork', 'Collaboration', 'Learning', 'Implementation'],
    meaning: 'Collaboration and teamwork are key to success. Your skills are valued by others.',
    reversedMeaning: 'Lack of teamwork, disharmony. You are struggling to work with others.',
    microQuest: 'Ask for feedback on a project you are working on.',
    element: 'Earth',
  },
  {
    id: 'pents_4',
    name: 'Four of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Saving', 'Security', 'Control', 'Conservation'],
    meaning: 'You are holding on tightly to what you have, seeking security. Be careful not to become too possessive.',
    reversedMeaning: 'Greed, materialism, letting go. You are either being greedy or learning to let go of control.',
    microQuest: 'Review your budget or savings plan. Are you saving for a goal?',
    element: 'Earth',
  },
  {
    id: 'pents_5',
    name: 'Five of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Financial loss', 'Poverty', 'Isolation', 'Worry'],
    meaning: 'You are facing financial hardship and feeling isolated. Do not be afraid to ask for help.',
    reversedMeaning: 'Recovery from financial loss, spiritual poverty. You are starting to recover from a difficult time.',
    microQuest: 'If you are struggling, reach out to a friend or resource for support.',
    element: 'Earth',
  },
  {
    id: 'pents_6',
    name: 'Six of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Generosity', 'Charity', 'Giving and receiving', 'Sharing wealth'],
    meaning: 'A time of generosity and charity. You are in a position to give or receive help.',
    reversedMeaning: 'Debt, selfishness, one-sided charity. The balance of giving and receiving is off.',
    microQuest: 'Give something today without expecting anything in return (it can be your time or a compliment).',
    element: 'Earth',
  },
  {
    id: 'pents_7',
    name: 'Seven of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Patience', 'Investment', 'Hard work', 'Perseverance'],
    meaning: 'You have worked hard and planted your seeds. Now is a time for patience as you wait for the harvest.',
    reversedMeaning: 'Lack of long-term vision, impatience. You are frustrated with the slow pace of results.',
    microQuest: 'Take a moment to appreciate the progress you have made so far on a long-term project.',
    element: 'Earth',
  },
  {
    id: 'pents_8',
    name: 'Eight of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Apprenticeship', 'Skill development', 'Mastery', 'Diligence'],
    meaning: 'You are honing your skills and working diligently towards mastery. Focus on the details.',
    reversedMeaning: 'Perfectionism, lack of ambition. You are either getting lost in details or not trying to improve.',
    microQuest: 'Dedicate 30 minutes to practicing a skill you want to improve.',
    element: 'Earth',
  },
  {
    id: 'pents_9',
    name: 'Nine of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Abundance', 'Luxury', 'Self-sufficiency', 'Financial independence'],
    meaning: 'You have achieved a level of success and can enjoy the fruits of your labor. A time of luxury and independence.',
    reversedMeaning: 'Financial dependency, living beyond your means. You are not as financially secure as you appear.',
    microQuest: 'Treat yourself to a small luxury today as a reward for your hard work.',
    element: 'Earth',
  },
  {
    id: 'pents_10',
    name: 'Ten of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Wealth', 'Family', 'Legacy', 'Long-term success'],
    meaning: 'You have created long-term success and stability for your family and future generations.',
    reversedMeaning: 'Family disputes, financial failure. The legacy you are building is unstable.',
    microQuest: 'Think about the legacy you want to leave. What is one thing you can do today to contribute to it?',
    element: 'Earth',
  },
  {
    id: 'pents_page',
    name: 'Page of Pentacles',
    arcana: 'Pentacles',
    keywords: ['New opportunities', 'Manifestation', 'Financial opportunity', 'Learning'],
    meaning: 'A new opportunity for growth in your career or finances is here. Stay grounded and be open to learning.',
    reversedMeaning: 'Lack of progress, procrastination. You are not taking advantage of the opportunities available.',
    microQuest: 'Learn something new related to your career or a practical skill.',
    element: 'Earth',
  },
  {
    id: 'pents_knight',
    name: 'Knight of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Hard work', 'Productivity', 'Routine', 'Conservatism'],
    meaning: 'Methodical and diligent effort is required. Stick to your routines and trust the process.',
    reversedMeaning: 'Boredom, stagnation, feeling "stuck". Your routine has become a rut, and it is time for a change.',
    microQuest: 'Complete a routine task with mindful attention to detail.',
    element: 'Earth',
  },
  {
    id: 'pents_queen',
    name: 'Queen of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Nurturing', 'Practical', 'Down-to-earth', 'Financial security'],
    meaning: 'You are a nurturing and practical provider. You create a warm and secure environment for yourself and others.',
    reversedMeaning: 'Financial insecurity, jealousy, smothering. Your focus on security has become unhealthy.',
    microQuest: 'Do something to make your home feel more comfortable and secure.',
    element: 'Earth',
  },
  {
    id: 'pents_king',
    name: 'King of Pentacles',
    arcana: 'Pentacles',
    keywords: ['Wealth', 'Business', 'Leadership', 'Security', 'Abundance'],
    meaning: 'You have achieved great success and abundance through your hard work and leadership. You are a master of the material world.',
    reversedMeaning: 'Greed, materialism, stubbornness. Your focus on wealth has become all-consuming.',
    microQuest: 'Share your expertise or resources to help someone else succeed.',
    element: 'Earth',
  },
];

export const ELEMENT_COLORS: { [key in TarotCard['element']]: string } = {
  Fire: 'text-[#FF7A1A]',
  Earth: 'text-[#29C26A]',
  Air: 'text-[#21C7F2]',
  Water: 'text-[#6E7BFF]',
};

export const ELEMENT_BORDERS: { [key in TarotCard['element']]: string } = {
    Fire: 'border-[#FF7A1A]',
    Earth: 'border-[#29C26A]',
    Air: 'border-[#21C7F2]',
    Water: 'border-[#6E7BFF]',
};

export const NUMEROLOGY_MEANINGS: { [key: number]: { theme: string, description: string } } = {
  1: { theme: "New Beginnings", description: "A day for independence, innovation, and planting new seeds." },
  2: { theme: "Duality & Partnership", description: "Focus on cooperation, harmony, and relationships." },
  3: { theme: "Creativity & Communication", description: "Express yourself, socialize, and embrace joy." },
  4: { theme: "Structure & Stability", description: "A day for hard work, planning, and building foundations." },
  5: { theme: "Change & Freedom", description: "Embrace adventure, expect the unexpected, and be flexible." },
  6: { theme: "Nurturing & Harmony", description: "Focus on family, home, and matters of the heart." },
  7: { theme: "Introspection & Wisdom", description: "A day for reflection, analysis, and spiritual connection." },
  8: { theme: "Abundance & Power", description: "Focus on career, finance, and personal authority." },
  9: { theme: "Completion & Culmination", description: "A time for release, forgiveness, and finishing cycles." },
};

export const ASTROLOGICAL_SIGNS = [
  'Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo',
  'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'
] as const;

// Define spread details
export const SPREAD_DETAILS: { [key in SpreadType]: { name: string; description: string; cardCount: number; isPremium: boolean; positions: string[] } } = {
  '3-card': {
    name: 'Three Card Spread',
    description: 'A quick overview of past, present, and future.',
    cardCount: 3,
    isPremium: false,
    positions: ['The Past', 'The Present', 'The Future'],
  },
  'the-great-work': {
    name: 'The Great Work',
    description: 'A 5-card spread for creative projects and personal growth.',
    cardCount: 5,
    isPremium: false,
    positions: ['The Foundation', 'The Challenge', 'The Action', 'The Goal', 'The Outcome'],
  },
  'celtic-cross': {
    name: 'Celtic Cross',
    description: 'A deep and comprehensive 11-card reading.',
    cardCount: 11,
    isPremium: true,
    positions: [
      '1. The Heart of the Matter',
      '2. The Challenge (Crossing)',
      '3. The Foundation (Below)',
      '4. The Past (Behind)',
      '5. The Crown (Above)',
      '6. The Future (Ahead)',
      '7. Your Attitude',
      '8. External Influences',
      '9. Hopes and Fears',
      '10. The Final Outcome',
      '11. Overall Theme'
    ],
  },
};
